Reworked action a bit

diff --git a/.github/workflows/samples.yaml b/.github/workflows/samples.yaml
--- a/.github/workflows/samples.yaml
+++ b/.github/workflows/samples.yaml
@@ -18,18 +18,27 @@ jobs:
         with:
           files:  |
             samples/*.py
-          output_renamed_files_as_deleted_and_added: "true"
 
       - name: Check Python samples
         env:
-          NEW_FILES: ${{ steps.changed_files.outputs.all_added_files }}
+          NEW_FILES: ${{ steps.changed_files.outputs.all_modified_files }}
+          README: samples/README.md
         run: |
           #!/bin/bash
           
-          for file in "${NEW_FILES}"; do
-            if ! grep -q $name samples/README.md; then
-              echo "Error: sample not listed in README ($name)"
-              exit 1
+          for file in ${NEW_FILES}; do
+            if [[ -f ${file} ]]; then
+              # File exists, so needs to be listed.
+              if ! grep -q $name ${README}; then
+                echo "Error: Sample not listed in README ($name)"
+                exit 1
+              fi
+            else
+              # File does not exist, ensure it's not listed
+              if grep -q $name ${README}; then
+                echo "Error: Sample should not be listed in README ($name)"
+                exit 1
+              fi
             fi
           done
 
@@ -46,17 +55,26 @@ jobs:
         with:
           files:  |
             samples/rest/*.sh
-          output_renamed_files_as_deleted_and_added: "true"
 
       - name: Check REST samples
         env:
-          NEW_FILES: ${{ steps.changed_files.outputs.all_added_files }}
+          NEW_FILES: ${{ steps.changed_files.outputs.all_modified_files }}
+          README: samples/rest/README.md
         run: |
           #!/bin/bash
           
-          for file in "${NEW_FILES}"; do
-            if ! grep -q $name samples/README.md; then
-              echo "Error: sample not listed in README ($name)"
-              exit 1
+          for file in ${NEW_FILES}; do
+            if [[ -f ${file} ]]; then
+              # File exists, so needs to be listed.
+              if ! grep -q $name ${README}; then
+                echo "Error: Sample not listed in README ($name)"
+                exit 1
+              fi
+            else
+              # File does not exist, ensure it's not listed
+              if grep -q $name ${README}; then
+                echo "Error: Sample should not be listed in README ($name)"
+                exit 1
+              fi
             fi
           done
